spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:KgK8kYuLFIT6b38+H+cB2E0GrL/C825hS6MlTg/E1/OcM4OMb/QFCldOmz3WjLYrr3LMk/6L7jajw0Bkgm0934e1p36Ta0gd9oYG+dWzBNc9Wto8+Asb1nZPGRm3Bu/oxCszzI5m7lzhc/WniWnWQErooPUGkjRn+KeQT0sFd7irBgFCweQnR4Xh6CqpCreajKEFDCJ3+unEtJHDZEsNY0gCeEE0odBH+zKRH1BpgKg=
    username: mpw:7mG/EMKw74oyiB/LMzqIqg==
    password: mpw:PABnKNLVmn27Oo362cuTtw==
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  redis:
    database: 8
    host: mpw:YzdftpXBBgLy7VmokWdrK4hjKB8WCW7bwcnfV6nB7t/xo2muj30soiTGS4XKPhAU
    port: 6379
    password: mpw:bZqFg950btNM/dsR0vycDA==
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mail:
    host: smtp.exmail.qq.com
    username: server@tduckapp.com
    password: 8rH69a47pV2qynVE

logging:
  level:
    com.tduck.cloud: debug
  config: classpath:logback-spring.xml

#  请求日志是否打印
platform:
  qq:
    oauth:
      appId: mpw:rk3097HYqXT7Vi2G2FviZg==
      secret: mpw:GMhX2wUES+IEzN7ew5tsNBnfn7qnYAwd4yboiePZJY7bvn26Pxo3P1BlbAkazhk/
  oss:
    ossType: 1
    endpoint: 12
    accessKeyId: mpw:WOF+Vhv3nd9ToNO8rR5IhV9HOk413qQnioFfywJxM+IIQ4mrgDdYwMKsnvbG3FQR
    accessKeySecret: mpw:5EqsGyYp3MbnnIf1xGKUCz2PK6LlkQ0udZBrT4CfQOAfxcHt+NsbLc8+vp7vscF1
    bucketName: tduck-cloud
    domain: https://qiniu.smileyi.top
  sms:
    secretId: mpw:W+RKqswyYOtgpv6UOni0TqBLkjsoOaXnHAgiXBZjiutn7r5TAwBJlJ48wA6bBilO
    secretKey: mpw:5zzzynMufvVYi34OmI9mQH07HtTLg3R7YTuil3DS+bNw9uIodim2pw5qkK9lNish
    appId: 1400461467
    sign: smileyi知识分享
    validateCodeTemplateId: 808150
    retrievePwdValidateCodeTemplateId: 809014
  front:
    baseUrl: https://demo.tduckapp.com/
    resetPwdUrl: https://demo.tduckapp.com//forget/password?code={}&email={}
    updateEmailUrl: https://demo.tduckapp.com/forget/validate?type=updateEmail&code={}&email={}

wx:
  mp:
    configs:
      - appId: mpw:LlPToLhvLcJzDSyXIo8zLZrXR1VjSoNWIK4GIzjKEic=
        secret: mpw:XjQD9w8yetuhWw9kte+itpW5d12sz8ZOw4FQheiq64WE/enJJwvki1WODCGANYUC
        token: mpw:bjdiFwY/AerwQGaplUBbdePohb3kRhb1k/KcoxNsN6k=
        aesKey:
server:
  port: 8998
